name: publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run packagr

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish NPM
        working-directory: ./dist
        run: |
          ls -l
          npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@ihk-gfi'
      - name: Publish Github
        working-directory: ./dist
        run: |
          ls -l
          npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB}}
